name: Python CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout reporsitory
      uses: actions/checkout@v3

    - name: set up python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: run test with Python
      run: |
        pytest
      

    
