name: Python CI with Docker 

on: 
  push:
    branches: ["main"]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout reporsitory
      uses: actions/checkout@v3

    - name: set up python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run test with Python
      run: |
        pytest
  

  build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to github docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tes-cicd:latest


    
